version: '3'
services:
  db:
    image: postgres
    environment:
      POSTGRES_PASSWORD: password
      POSTGRES_DB: bullettrain
  api:
    build:
      context: .
      dockerfile: api-dockerfile
    command: bash -c "pipenv run python manage.py migrate --noinput
              && pipenv run python manage.py collectstatic --noinput
              && pipenv run gunicorn --bind 0.0.0.0:8000 -w 3 app.wsgi"
    environment:
      DJANGO_DB_NAME: bullettrain
      DJANGO_DB_USER: postgres
      DJANGO_DB_PASSWORD: password
      DJANGO_DB_PORT: 5432
      DJANGO_ALLOWED_HOST: localhost
    ports:
     - "8000:8000"
    depends_on:
      - db
    links:
      - db:db
  web:
    build:
      context: .
      dockerfile: frontend-dockerfile
    command: bash -c "cd /usr/src && npm run dev"
    ports:
      - "8080:8080"